# Generated by Django 2.1.4 on 2019-01-21 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190121_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 14, 33, 53, 438266, tzinfo=utc)),
        ),
    ]
