# Generated by Django 2.1.4 on 2019-01-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190121_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeveragePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.TextField()),
                ('reference', models.TextField()),
            ],
        ),
    ]
